env:
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  import/prefer-default-export: 0,
  import/extensions: 0,
  import/no-unresolved: 0,
  no-unused-vars: ["error", { "argsIgnorePattern": "^_" }],
  no-return-await: 0,
  no-underscore-dangle: 0,
  class-methods-use-this: 0,
  no-param-reassign: 0
}
